remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Body Site Knowledge
description: [A short description of your site's purpose]
github: 
  is_project_page: false
  is_user_page: false
  show_downloads: false
